name: ludo_premium
description: Ludo Premium - Direct UPI
publish_to: 'none'
version: 1.0.0+20

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.2.2

flutter:
  uses-material-design: true