// File generated by FlutterFire CLI.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) { throw UnsupportedError('DefaultFirebaseOptions have not been configured for web'); }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android: return android;
      case TargetPlatform.iOS: throw UnsupportedError('DefaultFirebaseOptions have not been configured for ios');
      case TargetPlatform.macOS: throw UnsupportedError('DefaultFirebaseOptions have not been configured for macos');
      case TargetPlatform.windows: throw UnsupportedError('DefaultFirebaseOptions have not been configured for windows');
      case TargetPlatform.linux: throw UnsupportedError('DefaultFirebaseOptions have not been configured for linux');
      default: throw UnsupportedError('DefaultFirebaseOptions are not supported for this platform.');
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWLEeS-TrsVabQT9rltt5dXN0-omR9qBc', 
    appId: '1:472725834005:android:d6dde95567e0b44a8e411c', 
    messagingSenderId: '472725834005', 
    projectId: 'ludo-premium-50-e427e', 
    storageBucket: 'ludo-premium-50-e427e.firebasestorage.app',
    databaseURL: 'https://ludo-premium-50-default-rtdb.asia-southeast1.firebasedatabase.app',
  );
}